---
- name: Example playbook with handlers
  hosts: web_servers
  tasks:
    - name: Update web server configuration
      ansible.builin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
