---
- name: Deploy Web Application
  hosts: web_servers
  gather_facts: yes

  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - server_name: "example.com"
            root: "/var/www/html/example"

  tasks:
    - name: Ensure database is present
      community.mysql.mysql_db:
        name: mydb
        state: present

  collections:
    - community.mysql
