---
- name: Create EC2 instance
  hosts: all
  collections: amazon.aws
  tasks:
  - name: Start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "public-compute-instance"
      key_name: "prod-ssh-key"
      vpc_subnet_id: subnet-abcdefghi
      instance_type: t3.micro
      security_group: default
      network:
        assign_public_ip: true
      image_id: ami-123456
