---
- name: Append a line to a file
  hosts: all
  become: true
  tasks:
    - name: Append text to the file
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        create: yes
