all:
  children:
    webservers:
      hosts:
        web1.example.com:
        web2.example.com:
    databases:
      hosts:
        db1.example.com:
        db2.example.com:
      vars:
        db_port: 5432
  vars:
    ansible_user: admin
    ansible_port: 22
