---
- name: Install httpd on web servers
  hosts: webservers
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

- name: Upgrade all packages on database servers
  hosts: databases
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
