---
- name: Ensure a repository is added
  hosts: all
  become: yes
  tasks:
    - name: Add a GPG key
      ansible.builtin.rpm_key:
        state: present
        key: http://repo.example.com/RPM-GPG-KEY-example

    - name: Add a YUM repository
      ansible.builtin.yum_repository:
        name: example-repo
        description: "Example Repository"
        baseurl: http://repo.example.com/yum/
        enabled: yes
        gpgcheck: yes
        gpgkey: http://repo.example.com/RPM-GPG-KEY-example
